### ISSUE TITLE
Caevo fails with error: no dct found in ReichenbachDG13 sieve 

### ISSUE THREAD

**Issue by assaft** [nchambers/caevo#2]
Hello,

I'm trying to run caevo on the sentence: 

Between 1965 and 1975, the United States spent $111 billion on the war ($686 billion in FY 2008 dollars). This resulted in a large federal budget deficit. 

But it fails with an error:

WARNING: no dct found in ReichenbachDG13 sieve!
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at caevo.sieves.ReichenbachDG13.compareContexts(ReichenbachDG13.java:151)
        at caevo.sieves.ReichenbachDG13.annotate(ReichenbachDG13.java:103)
        at caevo.Main.runSieves(Main.java:257)
        at caevo.Main.markupAll(Main.java:708)
        at caevo.Main.markupRawText(Main.java:682)
        at caevo.Main.main(Main.java:781)
        ... 6 more

The problem is new and I encountered it right after pulling the latest commit ( 212a018de2c1ed879c03dda1056b1e3d3a72f91b). I'm attaching logs of execution from the master head and the previous commit (which doesn't have this problem).

[caevo_latest.txt](https://github.com/nchambers/caevo/files/61894/caevo_latest.txt)
[caevo_previous.txt](https://github.com/nchambers/caevo/files/61893/caevo_previous.txt)
[pair3_t.txt](https://github.com/nchambers/caevo/files/61895/pair3_t.txt)

**Comment by tc64** [comment]
Hi,
Thanks for reporting this! I think I know what is going on here. There is likely no document creation time (DCT) associated with the text in question. With the raw parameter passed to Main, CAEVO *should* not assume that a DCT will be provided. I should have time by tomorrow night, possibly earlier, to look into this and try to fix it.

Best,
Taylor

**Comment by tc64** [comment]
Hi,

The issue should be solved now, let me know if you still have an error.

Note that default.properties has a new entry, Main.dctHeuristic, with a default value of "none". You can keep this at none and if your document doesn't have a DCT specified, caevo will proceed as though there is no DCT. If you set the value to "setFirstDateAsDCT" then caevo will look for the first date timex and set the DCT to that date.

-Taylor

**Comment by assaft** [comment]
Hi,
Thanks, it looks good!
By the way, I plan to work with caevo in the next few months so I forked the repo in order to be free to insert new features and small bug fixes. You might want to look at it from time to time to see what I added. If I encounter critical things like this one, I'll report them here.
Best regards,
Assaf

**Comment by nchambers** [comment]
Assaf,
Thanks for reporting this. Please stay in touch if you make bug fixes. We'd
love to have you contribute and build it up for the benefit of everyone!

Nate

**Comment by tc64** [comment]
Assaf,
Yes, feel free to report any other bugs! I'm working on developing similar capabilities for Arabic text, so I'll be looking through the code quite a bit (though it will be a little while before I merge that branch). I'll check out what you're up to in the mean time.
-Taylor
